### PR TITLE
Remove [Xml]TreeBuilderActions and [Xml]TreeBuilderStep and move their implementations into [Xml]TreeBuilder

### PR DESCRIPTION
**Pull request by jbg**
See issue #258

---
This change is [Reviewable](https://reviewable.io/reviews/servo/html5ever/274)

### CODE REVIEW

**Comment by jdm** [comment]
Review ping, @nox.

**Comment by Ygg01** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r4.
Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/html5ever/274)*

**Pull request merged**
