### PR TITLE
Upgrade string-cache to 0.2.

### PR DESCRIPTION
**Pull request by SimonSapin**
r? @asajeffrey

[Review on Reviewable](https://reviewable.io/reviews/servo/html5ever/184)

### CODE REVIEW

**Comment by frewsxcv** [comment]
Travis fail in case you missed it

**Comment by SimonSapin** [comment]
Thank, looking.

**Comment by asajeffrey** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/html5ever/184)_

**Pull request merged**
