### PR TITLE
Removed has_parent_node and same_tree methods from TreeSink trait

### LINKED ISSUE #303: Remove `same_tree` and `has_parent_node` methods from the TreeSink trait
These methods are no longer used by the TreeBuilder and can be removed safely.

### PR DESCRIPTION
**Pull request by rozuur**
fixes #303 
Continued from https://github.com/servo/html5ever/pull/308

### CODE REVIEW

**Comment by cynicaldevil** [comment]
No need to create a new pull request each time someone requests changes :) Instead, code your changes, add them normally, and then commit them using `git commit --amend`. 
This overwrites your top most commit with your new changes. Use `git push -f *remote* *branch-name*` to force-push to your remote branch, the PR will update itself accordingly.

**Comment by rozuur** [comment]
@cynicaldevil Will remember it next time to update pull requests accordingly. Also, Rc[1] doesn't have a method to convert it to an option. Should I go ahead and update this pull request similar to #308 

1. https://doc.rust-lang.org/std/rc/struct.Rc.html

**Comment by rozuur** [comment]
@cynicaldevil Should I revert this commit?

**Comment by Ygg01** [comment]
@rozuur No need? You can just use [`git rebase -i`](https://git-scm.com/docs/git-rebase) followed by a `git push --force` to change this PR however you like.

**Comment by rozuur** [comment]
Reverted to older version, please recheck @cynicaldevil @Ygg01

**Comment by cynicaldevil** [comment]
@rozuur You need to bump the version numbers for the crates too, like I mentioned in the previous PR.

**Comment by rozuur** [comment]
@cynicaldevil bumped up the version numbers, let me know if anything is required.

**Comment by rozuur** [comment]
Thanks everyone 😄

**Comment by cynicaldevil** [comment]
Thanks for contributing!

**Pull request merged**
