### PR TITLE
Fix two typos

### PR DESCRIPTION
**Pull request by striezel**
This pull request fixes two typos.

### CODE REVIEW

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by striezel** [comment]
Relevant error of the [rustc 1.49 build](https://github.com/servo/html5ever/actions/runs/3119751916/jobs/5064354291):
```
  Downloaded once_cell v1.15.0
error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/once_cell-1.15.0/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
Error: Process completed with exit code 101.
```

The recently released version 1.15.0 of [once_cell](https://github.com/matklad/once_cell) bumped the MSRV to 1.56, as can be seen in the changelog: https://github.com/matklad/once_cell/blob/master/CHANGELOG.md
So possible solutions may include:
* Increase MSRV of html5ever to 1.56.0, too.
* Pin version of `once_cell` dependency to 1.14.0.

Both are probably out of scope for this pull request.

**Comment by striezel** [comment]
@jdm: Just saw the the MSRV / `once_cell` issue was taken care of in <https://github.com/servo/html5ever/pull/483>, so I rebased this against the current master. Builds should pass now.

@bors-servo retry

**Pull request merged**
