### PR TITLE
Run on Rust stable

### LINKED ISSUE #53: Build on Rust stable branch
Not for 1.0 necessarily, but at some point in 1.x.

The biggest obstacle is syntax extensions.  I have no clever ideas there except running `rustc-nightly --pretty expanded` and shipping that as the 1.x "source".

We should catalog all of the other obstacles here.

Servo itself will be on nightlies for a looooong time.

### PR DESCRIPTION
**Pull request by SimonSapin**
When the "unstable" Cargo feature is given, html5ever’s build script will use html5ever_macros as a library to generate or update `src/tree_builder/rules.expanded.rs`, which is part of the source tree.

(This feature also enables the corresponding features of tendril and string-cache.)

html5ever_macros is not a plugin anymore, but it still uses libsyntax and still behaves a lot like a syntax extension.

When "unstable" is *not* given, the build script checks that rules.expanded.rs is up to date (based on a hash of rules.rs) and fails if it’s not.

Tests also run on stable Rust on Travis-CI, but unfortunately most of them are disabled as they dynamically generated using internals of the `test` crate.

r? @Manishearth

Fixes #53
Closes #151

[Review on Reviewable](https://reviewable.io/reviews/servo/html5ever/151)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Don’t be deterred by the +2,936 diff stat, 2,497 of those are `src/tree_builder/rules.expanded.rs` :)

**Comment by Ygg01** [comment]
@SimonSapin: I'm wondering, is #112 still active? Will html5ever move to aster in future?

**Comment by SimonSapin** [comment]
I made this close #112, as https://github.com/servo/html5ever/issues/112#issuecomment-83190551 indicates that the motivation was stable Rust.

**Comment by Manishearth** [comment]
Reviewed 8 of 8 files at r1.
Review status: 4 of 39 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/html5ever/151)

**Comment by Manishearth** [comment]
Reviewed 7 of 7 files at r2.
Review status: 6 of 39 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/html5ever/151)

**Comment by Manishearth** [comment]
Reviewed 1 of 1 files at r3, 5 of 6 files at r4.
Review status: 7 of 39 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/html5ever/151)

**Comment by Manishearth** [comment]
Reviewed 1 of 6 files at r4.
Review status: 7 of 39 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/html5ever/151)

**Comment by Manishearth** [comment]
Reviewed 1 of 1 files at r5, 9 of 9 files at r6, 18 of 18 files at r7.
Review status: 24 of 39 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/html5ever/151)

**Comment by Manishearth** [comment]
Reviewed 6 of 6 files at r8, 2 of 2 files at r9, 2 of 2 files at r10, 6 of 6 files at r11, 1 of 1 files at r12, 3 of 3 files at r13, 1 of 1 files at r14.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[examples/noop-tokenize.rs, line 29 \[r11\]](https://reviewable.io:443/reviews/servo/html5ever/151#-JvZK6gXYBWsfnw8I-hJ)** ([raw file](https://github.com/servo/html5ever/blob/6f394c98283dd71e3ab24044aad4b2937b100879/examples/noop-tokenize.rs#L29)):</sup>
Do we have benchmarks? Because this would affect them. It's also possible to write your own blackbox via FFI.

---

<sup>**[examples/print-tree-actions.rs, line 126 \[r11\]](https://reviewable.io:443/reviews/servo/html5ever/151#-JvZJx4QOCkZOc9xceS7)** ([raw file](https://github.com/servo/html5ever/blob/6f394c98283dd71e3ab24044aad4b2937b100879/examples/print-tree-actions.rs#L126)):</sup>
Can we leave a FIXME here?

---

<sup>**[macros/src/pre_expand.rs, line 48 \[r14\]](https://reviewable.io:443/reviews/servo/html5ever/151#-JvZKurSsOA9Cycgfxqz)** ([raw file](https://github.com/servo/html5ever/blob/1bc67dc4718a84e9b05418b5b1d2f2d6d4a5b9f1/macros/src/pre_expand.rs#L48)):</sup>
no need for as_str here

---

<sup>**[tests/tokenizer.rs, line 425 \[r9\]](https://reviewable.io:443/reviews/servo/html5ever/151#-JvZIqBESEaGHusUzGJW)** ([raw file](https://github.com/servo/html5ever/blob/b5a5a8b6a39c14416ae47e523ab82bb7db8092bf/tests/tokenizer.rs#L425)):</sup>
Why did we do this earlier?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/html5ever/151)

**Comment by SimonSapin** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[examples/noop-tokenize.rs, line 29 \[r11\]](https://reviewable.io:443/reviews/servo/html5ever/151#-JvZK6gXYBWsfnw8I-hJ)** ([raw file](https://github.com/servo/html5ever/blob/6f394c98283dd71e3ab24044aad4b2937b100879/examples/noop-tokenize.rs#L29)):</sup>
There is `benches/tokenizer.rs`, but it doesn’t use this file. (It also looks like it’s not built in CI.)

---

<sup>**[examples/print-tree-actions.rs, line 126 \[r11\]](https://reviewable.io:443/reviews/servo/html5ever/151#-JvZJx4QOCkZOc9xceS7)** ([raw file](https://github.com/servo/html5ever/blob/6f394c98283dd71e3ab24044aad4b2937b100879/examples/print-tree-actions.rs#L126)):</sup>
Done

---

<sup>**[macros/src/pre_expand.rs, line 48 \[r14\]](https://reviewable.io:443/reviews/servo/html5ever/151#-JvZKurSsOA9Cycgfxqz)** ([raw file](https://github.com/servo/html5ever/blob/1bc67dc4718a84e9b05418b5b1d2f2d6d4a5b9f1/macros/src/pre_expand.rs#L48)):</sup>
Removed.

---

<sup>**[tests/tokenizer.rs, line 426 \[r9\]](https://reviewable.io:443/reviews/servo/html5ever/151#-JvZIqBESEaGHusUzGJW)** ([raw file](https://github.com/servo/html5ever/blob/b5a5a8b6a39c14416ae47e523ab82bb7db8092bf/tests/tokenizer.rs#L426)):</sup>
`main` is not significant when building with `--test`, the real `main` function is provided by the test harness. Previously, `#[start]` was used to override that `main` function. I removed usage of `#[start]` because it is unstable, but that’s kinda moot since I didn’t manage to completely port this file to stable. (It uses the `test` crate to generate tests dynamically.)

So, with 70e30395c9b0e43a353c151b27803f7211caa630 we have one test harness instance that finds a single test that happens to be called `main` and creates another test harness instance. The output looks like:

```
     Running target/debug/tokenizer-dcf7263c41100ab8

running 1 test

running 13344 tests
test tok: contentModelFlags.test: End tag closing RCDATA or RAWTEXT (case-insensitivity) (in state RawData(Rawtext)) ... ok
test tok: contentModelFlags.test: End tag closing RCDATA or RAWTEXT (case-insensitivity) (in state RawData(Rcdata)) ... ok
[many more lines…]
test tb: webkit02.dat-7 ... ok

test result: ok. 1338 passed; 0 failed; 211 ignored; 0 measured

test main ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured
```

Maybe we’re better off reverting to using `#[start]` until we find a way to actually run these tests on stable Rust?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/html5ever/151)

**Comment by Manishearth** [comment]
Reviewed 2 of 2 files at r15, 1 of 1 files at r16.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/html5ever/151)

**Pull request merged**
