### PR TITLE
Rustup to 4be79d6ac

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by kmcallister** [comment]
Needs a rebase. I believe we got most of this in #71.

**Comment by kmcallister** [comment]
Are there any changes here that we've yet to make?

**Comment by Manishearth** [comment]
I believe it still fails some tests. I completely forgot about this PR, will get to it today :)

-----Original Message-----

**Comment by Manishearth** [comment]
See #82

**Pull request closed without merging**
