### PR TITLE
Fix breaking OSS-Fuzz coverage build

### PR DESCRIPTION
**Pull request by DavidKorczynski**

### CODE REVIEW

**Comment by CYBAI** [comment]
I guess this is inspired by https://github.com/rust-lang/regex/issues/757 👀

**Comment by DavidKorczynski** [comment]
> I guess this is inspired by [rust-lang/regex#757](https://github.com/rust-lang/regex/issues/757)

Yes, the issue happened across essentially all rust projects on OSS-Fuzz.

**Comment by emilio** [comment]
Looks sane, thanks!

@bors-servo r+

**Comment by CYBAI** [comment]
> Yes, the issue happened across essentially all Rust projects on OSS-Fuzz.

Thanks for the PR!!!

**Pull request merged**
