### PR TITLE
Update string-cache in html5ever-atoms.

### PR DESCRIPTION
**Pull request by emilio**
This change is [Reviewable](https://reviewable.io/reviews/servo/html5ever/264)

### CODE REVIEW

**Comment by emilio** [comment]
(Let me know if this should be breaking, but I don't think so)

**Comment by nox** [comment]
It's a breaking change because `string_cache::Atom` is exposed.

**Comment by nox** [comment]
So it's a breaking change in `html5ever` and `xml5ever` too.

**Comment by emilio** [comment]
Sure, but its API isn't changed, right? Oh, I guess you could have another older string_cache or something like that/

**Comment by nox** [comment]
Yes, using a type from a dependency with a different breaking version than before is a change in API, because `Atom` isn't the same `Atom`.

**Comment by emilio** [comment]
Ammended

**Pull request merged**
