### PR TITLE
Zero copy parsing take 3

### PR DESCRIPTION
**Pull request by kmcallister**
This includes the [tendril](https://github.com/kmcallister/tendril) integration which is desired for `document.write`. The only missing piece afaik is fixing up the C API (or temporarily disabling it, but I'd rather not).

I won't have time to finish up this PR but I can answer questions for sure.

(Was #141.)

[Review on Reviewable](https://reviewable.io/reviews/servo/html5ever/142)

### CODE REVIEW

**Comment by SimonSapin** [comment]
What do you want to do with https://github.com/kmcallister/tendril ? Maintain it (we send PRs to you), let us fork it and diverge, give us write access, transfer it?

**Comment by SimonSapin** [comment]
Same question for https://github.com/kmcallister/futf/

**Comment by SimonSapin** [comment]
I read through futf, tendril, and this PR. It all looks good. There are lots of good ideas in tendril, I like it :)

---

Review status: all files reviewed, all discussions resolved, some commit checks failed.
Reviewed files:
- benches/tokenizer.rs @ r1
- capi/Cargo.toml @ r1
- capi/include/html5ever.h @ r1
- capi/src/lib.rs @ r1
- capi/src/tokenizer.rs @ r1
- Cargo.toml @ r1
- dom_sink/Cargo.toml @ r1
- dom_sink/src/common.rs @ r1
- dom_sink/src/lib.rs @ r1
- dom_sink/src/owned_dom.rs @ r1
- dom_sink/src/rcdom.rs @ r1
- examples/html2html.rs @ r1
- examples/noop-tokenize.rs @ r1
- examples/noop-tree-builder.rs @ r1
- examples/print-rcdom.rs @ r1
- examples/print-tree-actions.rs @ r1
- examples/tokenize.rs @ r1
- src/driver.rs @ r1
- src/lib.rs @ r1
- src/tokenizer/buffer_queue.rs @ r1
- src/tokenizer/char_ref/mod.rs @ r1
- src/tokenizer/interface.rs @ r1
- src/tokenizer/mod.rs @ r1
- src/tree_builder/actions.rs @ r1
- src/tree_builder/data.rs @ r1
- src/tree_builder/interface.rs @ r1
- src/tree_builder/mod.rs @ r1
- src/tree_builder/rules.rs @ r1
- src/tree_builder/types.rs @ r1
- src/util/smallcharset.rs @ r1
- src/util/str.rs @ r1
- tests/serializer.rs @ r1
- tests/tokenizer.rs @ r1
- tests/tree_builder.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/html5ever/142)

**Comment by kmcallister** [comment]
I think I'll transfer tendril and futf to the Servo org.

**Comment by kmcallister** [comment]
Done :)

**Comment by SimonSapin** [comment]
Great, thanks!

**Comment by SimonSapin** [comment]
@kmcallister the C API changes look good to me, and `cargo test --manifest-path capi/Cargo.toml` passes (although it runs zero test). What’s missing?

**Pull request merged**
