### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by svenfoo**
Another wave of changes suggested by Clippy. There are some warnings left, but this is as far as I will get today.

### CODE REVIEW

**Comment by svenfoo** [comment]
The build fails because of an outdated Rust version on the Linux build pipeline. I can of course revert the problematic change, it needs at least Rust 1.40. However I would first like to ask what the minimum Rust version is that html5ever is targeting. Is there a good reason to use Rust 1.36 on the CI?

**Comment by Ygg01** [comment]
> Is there a good reason to use Rust 1.36 on the CI?

I think the only valid reason is if servo runs only on 1.36. It's one of few major dependents.

**Comment by svenfoo** [comment]
I have removed two commits that required a version of Rust newer than 1.36.

**Comment by svenfoo** [comment]
Is there a reason why this is not merged? Is there anything you'd like me to change?

**Comment by svenfoo** [comment]
I've added two commits to fix the warnings caused the Travis CI build to fail.

**Comment by jdm** [comment]
The error on nightly is https://github.com/bheisler/TinyTemplate/issues/16.

**Pull request merged**
