### PR TITLE
Add licenses to all crates.

### LINKED ISSUE #365: Include LICENSE files into sub-crates
We need that in order to package mark5ever and such in Fedora.

### PR DESCRIPTION
**Pull request by jdm**
Fixes #365.

### CODE REVIEW

**Comment by Ygg01** [comment]
@jdm do you need this merged?

**Comment by jdm** [comment]
Yep.

**Comment by Ygg01** [comment]
r+

**Comment by Ygg01** [comment]
Let me see if incantations are correct: @bors-servo r+

**Pull request merged**
