### PR TITLE
Change mac dependeny to crates.io.

### PR DESCRIPTION
**Pull request by metajack**
r? @kmcallister

### CODE REVIEW

**Comment by SimonSapin** [comment]
There’s also https://github.com/servo/html5ever/compare/dev . @kmcallister, was there an issue with that branch?

**Comment by kmcallister** [comment]
I'm not sure; `dev` is just a scratch branch though.

**Comment by metajack** [comment]
@SimonSapin sounds like you can r+ this then

**Comment by SimonSapin** [comment]
I’ll finish what’s in the `dev` branch instead, it includes this change.

**Pull request closed without merging**
