### PR TITLE
Remove the C API

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/html5ever/204)

### CODE REVIEW

**Comment by SimonSapin** [comment]
```
+cargo test --manifest-path capi/Cargo.toml
error: manifest path `capi/Cargo.toml` does not exist
```

**Comment by Ygg01** [comment]
Why is C API being removed?

**Comment by nox** [comment]
Because, to quote @SimonSapin:

> it’s been broken for a long time, and it only has tokenization

And also:

> 14:55 <•SimonSapin> ManishCloud jdm nox: I have some experiments at https://github.com/SimonSapin/html5ever-python
> 14:55 <•SimonSapin> python parts aside this includes a C-compatible ABI

**Comment by RReverser** [comment]
> it’s been broken for a long time, and it only has tokenization

Well, then fixing and extending is perhaps a better option that removing?

**Comment by nox** [comment]
It's been broken for a long time and nobody cared.

**Comment by RReverser** [comment]
@nox Well, I do care because want to use html5ever from our codebase. As said in #203, actually trying to fix at the moment.

**Comment by SimonSapin** [comment]
@RReverser you likely want to use the parser (tree builder) and don’t care about the tokenizer in isolation. At this point what would be needed is more of a complete rewrite than fixing up existing stuff.

If you want to invest in this I’d recommend starting with a copy of https://github.com/SimonSapin/html5ever-python/blob/master/rust-glue/lib.rs . It doesn’t have to be in the servo/html5ever repository.

As you can see, in that C API strings are only exposed as (pointer, length) pairs. The details of string-cache and tendril are kept within Rust-land. This is a choice I made to manage the complexity. Depending on the application a different choice might make sense.

**Comment by RReverser** [comment]
@SimonSapin Actually I'm interested exactly in tokenizer at the moment (as mentioned in previous issues).

**Pull request merged**
