### PR TITLE
reexport string_cache

### PR DESCRIPTION
**Pull request by LuoZijun**
reexport string_cache

### CODE REVIEW

**Comment by SimonSapin** [comment]
Out of curiosity: why? Do you want to use string-cache to define more types yourself, or is it also needed somehow to use with the existing `LocalName`, `Namespace`, and `Prefix` types?

**Comment by LuoZijun** [comment]
@SimonSapin yes, like this : https://github.com/tbodt/htmlpyever/blob/master/glue.rs#L355

**Comment by SimonSapin** [comment]
Does `LocalName::from` not work?

**Comment by LuoZijun** [comment]
it work. sry, my mistake.

but i can't not find interface ( `LocalName::from` ) in this document page: https://doc.servo.org/markup5ever/type.LocalName.html

**Pull request closed without merging**
