### PR TITLE
Use associated types

### PR DESCRIPTION
**Pull request by kmcallister**
r? @Manishearth

### CODE REVIEW

**Comment by kmcallister** [comment]
Fixes #66.

**Comment by Manishearth** [comment]
r+

**Comment by Manishearth** [comment]
Probably should set up Travis for h5e, might take a crack at this tomorrow.

**Comment by kmcallister** [comment]
It's already set up, did you have a particular change in mind?

**Comment by Manishearth** [comment]
Huh, somehow it was missing from my GitHub view. Came back on a refresh. *shrug*

**Pull request merged**
