### PR TITLE
Update html5lib-tests

### LINKED ISSUE #459: html5ever lags far behind on html5lib-tests
html5ever's submodule checkout of html5lib-tests is 4 years old. While attempting to update it and add missing features to the test harness, I saw that it fails a signifiicant amount of tests in there. It also _hangs up_ on some of them.

I noticed this while fuzzing html5ever together with [html5gum](https://github.com/untitaker/html5gum) and finding a small testcase (https://github.com/html5lib/html5lib-tests/pull/140) that the fuzzer found.

I'll open the PR with the WIP submodule update in a second

### PR DESCRIPTION
**Pull request by untitaker**
Follow-up items:

* More precise errors
* There is still large divergence between some of the states and their names in code vs spec. It's just that there's no testcase for them.

I'm also fuzzing this branch continuously against https://github.com/untitaker/html5gum using `FUZZ_HTML5EVER=1` to find more bugs, but they only cover the tokenizer. Some bugfixes have been made and corresponding regression tests added in a `regression.test` file.

Fixes #459.

### CODE REVIEW

**Comment by jdm** [comment]
What makes this a WIP?

**Comment by untitaker** [comment]
Hmm, in the sense that it's not mergeable as-is.

**Comment by untitaker** [comment]
eh, I'm working on this now.

* Some of the testsuite format has changed. Errors are no longer tokens, they're their own separate array entry with line/col/code.
* Ignoring line/col, the code does not match your human-readable errors at all. Do we want to make an effort assimilating those to what html5lib-tests prescribes?

that's all there is to tokenizer tests, haven't looked at treebuilder tests yet. That said I am not really familiar with how treebuilding is done in the spec, so this could take quite a while.

**Comment by jdm** [comment]
Good question about error codes. I suspect a decent way to handle that would be to make an actual error enum that gets passed to emit_error, and then make the html5lib test harness map those error variants to the codes that the html5lib tests expect.

That being said, I'm inclined to file an issue about that and ignore specific error content for right now.

**Comment by untitaker** [comment]
I don't have the motivation to work on this further, but at the same time I think that the fixes already present in the PR are somewhat important to get merged.

@jdm what do you think about me skipping all remaining test failures and merging as-is otherwise? I.e what you suggested for error locations, but for all test failures. I fear that master might introduce changes that do not pass latest html5lib-tests. 

tokenizer test status:

```
test result: FAILED. 14053 passed; 3 failed; 0 ignored; 0 measured
```

tree builder test status:

```
test result: FAILED. 3407 passed; 64 failed; 0 ignored; 0 measured
```

**Comment by untitaker** [comment]
The tokenizer tests are fixed, except for one DoS case, that also gets stuck on master:

```
{"description": "Very long undefined named entity in body",
"input":"&ammmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmp;",
"output": [["Character", "&ammmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmp;"]],
"errors":[
    { "code": "unknown-named-character-reference", "line": 1, "col": 950 }
]}
```

tree builder tests has 60 test failures remaining.. some help/guidance on how to proceed would be welcome

**Comment by untitaker** [comment]
@jdm all tests are fixed. can you take a look?

**Comment by EdorianDark** [comment]
@mrobinson Can you take a look maybe?

**Review by mrobinson — APPROVED** [review]

**Pull request merged**
